{% set name = "genewalk" %}
{% set version = "1.1.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: "10e58f27c30079ff2c555fce6b95ea6104fb0067a9d0bfe756993e911e35f719"

build:
  number: 0
  entry_points:
    - genewalk = genewalk.cli:main
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - gensim
    - goatools
    - indra
    - networkx >=2.1
    - numpy
    - pandas
    - pip
    - python
    - scipy >=1.3.0
  run:
    - gensim
    - goatools
    - indra
    - networkx >=2.1
    - numpy
    - pandas
    - python
    - scipy >=1.3.0

test:
  imports:
    - genewalk
    - genewalk.tests
  commands:
    - genewalk --help
  requires:
    - nose

about:
  home: "https://github.com/churchmanlab/genewalk"
  license: "BSD"
  license_family: "BSD"
  license_file: ""
  summary: "Determine gene function based on network embeddings."
  doc_url: "https://genewalk.readthedocs.io/en/latest/"
  dev_url: ""

extra:
  recipe-maintainers:
    - bgyori
